### PR TITLE
TST: fix 3 bugs in `NPYReader` related to reading from directories which lack density files

### PR DESCRIPTION
**Pull request by neutrinoceros**

### CODE REVIEW

**Comment by volodia99** [comment]
I think there is a bug 6/3 compared to v0.12.1 :grimacing:

Here is the structure of my reduced dataset: 
- testdir
    - idefix.ini
    - header
        - header_vertical_at_midplane.json
    - vx1
        - _vertical_at_midplane_VX1.1200.npy

Here is my script : 
```python

from nonos.api import GasDataSet
dsvm = GasDataSet(1200, operation="vertical_at_midplane", directory="testdir")

```
I recover this error with your patch:
```python-traceback

FileNotFoundError: Failed to locate a file matching prefix='vertical_at_midplane' and output_number=1200

```

What is funny is that using the deprecated function from_npy gives the same error, but running from_npy in the tag v0.12.1 works fine! If you want to test it yourself I can give you the whole directory (2.1 Mo so that should be fine). Note that it works with `latitudinal_projection` :thinking:

**Comment by neutrinoceros** [comment]
> What is funny is that using the deprecated function from_npy gives the same error

that's because I didn't just deprecate it, I also re-routed it so it actually calls the same code

**Comment by neutrinoceros** [comment]
I don't think I need the actual dataset to test it. I'll let you know !

**Comment by volodia99** [comment]
OK I know why and I have a patch, incoming!

**Comment by volodia99** [comment]
Actually I cannot push on your branch.
One solution is to replace `[A-Z]` by `[A-Z0-9]` for `<field_name>` (both in `_filename_re` and in `parse_output_number_and_filename` method)

**Pull request merged**
